package lv.id.bure.www;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JLabel;
import javax.swing.ScrollPaneConstants;

public class LicenseFrame extends JFrame{
	
	private static final long serialVersionUID = 1L;
	
	public LicenseFrame() {
		// Generated by window builder
		setTitle("License");
		setResizable(false);
		setBounds(100, 100, 490, 390);
		JPanel contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));

		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JButton btnOkButton = new JButton("OK");
		btnOkButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				// Close window by pressing OK button
				setVisible(false);
			}
		});
		btnOkButton.setBounds(15, 317, 89, 23);
		contentPane.add(btnOkButton);
		
		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
		scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		scrollPane.setBounds(15, 42, 449, 264);
		contentPane.add(scrollPane);
		
		JTextArea txtrCopyrightcThis = new JTextArea();
		// License text added as a string constant
		final String LICENSE_STR =
			"    The Investor's clock shows the time in different time zones.\r\n" + 
            "    Copyright (C) 2023-2024 Sergejs Bure.\r\n\r\n" + 
	        "    This program is free software: you can redistribute it and/or modify\r\n" + 
            "    it under the terms of the GNU General Public License as published by\r\n" + 
	        "    the Free Software Foundation, either version 3 of the License, or\r\n" + 
            "    (at your option) any later version.\r\n\r\n" +
	        "    This program is distributed in the hope that it will be useful,\r\n" +
            "    but WITHOUT ANY WARRANTY; without even the implied warranty of\r\n" +
	        "    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\r\n" +
            "    See the GNU General Public License for more details.\r\n\r\n" + 
	        "    OpenJDK 21.0.2, an implementation of the Java SE 21 Platform,\r\n" +
            "    is distributed under the GNU General Public License, version 2,\r\n" +
            "    with the Classpath Exception.\r\n\r\n" +
	        "    You should have received a copy of the GNU General Public License\r\n" + 
            "    along with this program.  If not, see <https://www.gnu.org/licenses/>.";
		txtrCopyrightcThis.setEditable(false);
		txtrCopyrightcThis.setText(LICENSE_STR);
		scrollPane.setViewportView(txtrCopyrightcThis);
		
		JLabel lblMainLabel = new JLabel("The Investor's clock is licensed under the GNU General Public License.");
		lblMainLabel.setBounds(15, 11, 449, 14);
		contentPane.add(lblMainLabel);
	}

}
